<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="141" started-at="2020-01-21T14:45:23 IST" finished-at="2020-01-21T14:45:23 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="141" started-at="2020-01-21T14:45:23 IST" finished-at="2020-01-21T14:45:23 IST">
      <class name="Products.Products_Delete">
        <test-method status="PASS" signature="setup()[pri:0, instance:Products.Products_Delete@610694f1]" name="setup" is-config="true" duration-ms="4989" started-at="2020-01-21T14:45:18 IST" finished-at="2020-01-21T14:45:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Products_Delete_TC01()[pri:0, instance:Products.Products_Delete@610694f1]" name="Products_Delete_TC01" duration-ms="62" started-at="2020-01-21T14:45:23 IST" description=" validate response" finished-at="2020-01-21T14:45:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Products_Delete_TC01 -->
        <test-method status="PASS" signature="Products_Delete_response_code_TC02()[pri:0, instance:Products.Products_Delete@610694f1]" name="Products_Delete_response_code_TC02" duration-ms="0" started-at="2020-01-21T14:45:23 IST" description=" validate response_code" finished-at="2020-01-21T14:45:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Products_Delete_response_code_TC02 -->
        <test-method status="FAIL" signature="Products_Delete_response_time_TC03()[pri:0, instance:Products.Products_Delete@610694f1]" name="Products_Delete_response_time_TC03" duration-ms="0" started-at="2020-01-21T14:45:23 IST" description=" validate response_time" finished-at="2020-01-21T14:45:23 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [1508]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [1508]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:729)
at org.testng.Assert.assertEquals(Assert.java:739)
at Products.Products_Delete.Products_Delete_response_time_TC03(Products_Delete.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Products_Delete_response_time_TC03 -->
      </class> <!-- Products.Products_Delete -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
